[package]
name = "pingr"
version = "0.1.0"
authors = ["Tobias Kerst <tobias.kerst@tobscore.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4"
log = "0.4"
simple_logger = "1.3"